.TH "SAdrsStruct" 3 "Jeudi Mai 18 2017" "Instruments" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SAdrsStruct \- 
.SH SYNOPSIS
.br
.PP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "AnsiString \fBDeviceName\fP"
.br
.ti -1c
.RI "AnsiString \fBAddress\fP"
.br
.ti -1c
.RI "AnsiString \fBLibrary\fP"
.br
.ti -1c
.RI "AnsiString \fBDeviceType\fP"
.br
.ti -1c
.RI "AnsiString \fBFDescription\fP"
.br
.ti -1c
.RI "AnsiString \fBComment\fP"
.br
.ti -1c
.RI "int \fBInUse\fP"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Instruments à partir du code source\&.
