.TH "D:/cpp/simu_cpp/src/instruments/SBenchAdr.h" 3 "Fri Apr 14 2017" "Simulateur Banc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/cpp/simu_cpp/src/instruments/SBenchAdr.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Classes\&.hpp>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <io\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSAdrsStruct\fP"
.br
.ti -1c
.RI "class \fBSBenchAdrs\fP"
.br
.ti -1c
.RI "class \fBSBenchAdrComp\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef DynamicArray< \fBSAdrsStruct\fP > \fBSAdrsArray\fP"
.br
.ti -1c
.RI "typedef DynamicArray< AnsiString > \fBT1DStringArray\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef DynamicArray< \fBSAdrsStruct\fP > \fBSAdrsArray\fP"

.SS "typedef DynamicArray< AnsiString > \fBT1DStringArray\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Simulateur Banc from the source code\&.
