.TH "SBenchAdrs" 3 "Jeudi Mai 18 2017" "Instruments" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SBenchAdrs \- 
.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBSAdrsStruct\fP * \fBGetDevice\fP (AnsiString DeviceName)"
.br
.ti -1c
.RI "\fBSBenchAdrs\fP (AnsiString AFileName, AnsiString ASection='')"
.br
.ti -1c
.RI "void \fBSave\fP (void)"
.br
.ti -1c
.RI "T1DStringArray \fBSepareTab\fP (AnsiString Str_i, AnsiString Separateur_i)"
.br
.in -1c
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "AnsiString \fBTitle\fP"
.br
.ti -1c
.RI "SAdrsArray \fBAdrArray\fP"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Instruments à partir du code source\&.
