.TH "D:/cpp/simu_cpp/src/instruments/vsim_C.h" 3 "Fri Apr 14 2017" "Simulateur Banc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/cpp/simu_cpp/src/instruments/vsim_C.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Gpib_Interface_C\&.h'\fP
.br
\fC#include 'TBenchAdr\&.h'\fP
.br
\fC#include 'GpibObserver\&.h'\fP
.br
\fC#include 'vdescription_C\&.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <IniFiles\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvsim_C\fP"
.br
.RI "\fIdefinit la classe virtuelle des instruments simulés \&. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBVINST_DEFAULT_ESR_MASK\fP   0x3C"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef DynamicArray< AnsiString > \fBT1DStringArray\fP"
.br
.RI "\fIdefinition d'un tableau 1D dynamique de String \&. \fP"
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBVINST_DEFAULT_ESR_MASK\fP   0x3C"

.SH "Typedef Documentation"
.PP 
.SS "typedef DynamicArray< AnsiString > \fBT1DStringArray\fP"

.PP
definition d'un tableau 1D dynamique de String \&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Simulateur Banc from the source code\&.
