.TH "Frequency" 3 "Jeudi Mai 18 2017" "Equipements" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Frequency \- 
.SH SYNOPSIS
.br
.PP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "double \fBfrequency_Start_In\fP"
.br
.ti -1c
.RI "double \fBfrequency_Stop_In\fP"
.br
.ti -1c
.RI "double \fBbandwidth\fP"
.br
.ti -1c
.RI "double \fBstep\fP"
.br
.ti -1c
.RI "double \fBpower\fP"
.br
.ti -1c
.RI "double \fBfrequency_Min\fP"
.br
.ti -1c
.RI "double \fBfrequency_Max\fP"
.br
.ti -1c
.RI "double \fBfrequency_Ol\fP"
.br
.ti -1c
.RI "double \fBpower_Ol\fP"
.br
.ti -1c
.RI "double \fBpower_min\fP"
.br
.ti -1c
.RI "double \fBpower_max\fP"
.br
.ti -1c
.RI "double \fBpower_in\fP"
.br
.ti -1c
.RI "double \fBgain\fP"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Equipements à partir du code source\&.
