.TH "Rx_C" 3 "Jeudi Mai 18 2017" "Equipements" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rx_C \- 
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBvirtual_receiver_C\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "void \fBInitEqpt\fP (TIniFile *file)"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Equipements à partir du code source\&.
