.TH "virtual_tmtc_C" 3 "Jeudi Mai 18 2017" "Equipements" \" -*- nroff -*-
.ad l
.nh
.SH NAME
virtual_tmtc_C \- 
.SH SYNOPSIS
.br
.PP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "__property bool \fBTm_Status\fP = {read = getTm_Status, write = setTm_Status}"
.br
.ti -1c
.RI "__property bool \fBTm_ON_OFF\fP = {read = getTm_ON_OFF, write = setTm_ON_OFF}"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Equipements à partir du code source\&.
