.TH "D:/cpp/simu_cpp/src/equipment/virtual_alim_C.h" 3 "Fri Apr 14 2017" "Simulateur Banc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/cpp/simu_cpp/src/equipment/virtual_alim_C.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvirtual_alim_C\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBvirtual_alim_\fP   CH"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBvirtual_alim_\fP   CH"

.SH "Author"
.PP 
Generated automatically by Doxygen for Simulateur Banc from the source code\&.
