.TH "Utils::GPIB_T" 3 "Mercredi Avril 12 2017" "GPIB Interface" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utils::GPIB_T \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Gpib_Enum\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBTYPE_GPIB\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBId_Interface\fP"
.br
.ti -1c
.RI "int \fBAdr_Primaire\fP"
.br
.ti -1c
.RI "int \fBAdr_secondaire\fP"
.br
.ti -1c
.RI "bool \fBcontroler_system\fP"
.br
.ti -1c
.RI "int \fBtimeout\fP"
.br
.ti -1c
.RI "bool \fBEOI\fP"
.br
.ti -1c
.RI "\fBGPIB_STATUS\fP \fBstatus\fP"
.br
.ti -1c
.RI "\fBGPIB_BUSDATA\fP \fBStatus_bus\fP"
.br
.in -1c
.SH "Documentation des données membres"
.PP 
.SS "int \fBUtils::GPIB_T::Adr_Primaire\fP"

.SS "int \fBUtils::GPIB_T::Adr_secondaire\fP"

.SS "bool \fBUtils::GPIB_T::controler_system\fP"

.SS "bool \fBUtils::GPIB_T::EOI\fP"

.SS "int \fBUtils::GPIB_T::Id_Interface\fP"

.SS "\fBGPIB_STATUS\fP \fBUtils::GPIB_T::status\fP"

.SS "\fBGPIB_BUSDATA\fP \fBUtils::GPIB_T::Status_bus\fP"

.SS "int \fBUtils::GPIB_T::timeout\fP"

.SS "\fBTYPE_GPIB\fP \fBUtils::GPIB_T::type\fP"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour GPIB Interface à partir du code source\&.
