.TH "D:/cpp/simu_cpp/src/instruments/Alim/SAlimentations.h" 3 "Fri Apr 14 2017" "Simulateur Banc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/cpp/simu_cpp/src/instruments/Alim/SAlimentations.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'virtual_alimentation_C\&.h'\fP
.br
\fC#include 'hp661xxa_C\&.h'\fP
.br
\fC#include 'SBenchAdr\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSAlimentations\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSAlimEnum\fP { \fBalDebug\fP, \fBalAuto\fP, \fBalDAC488\fP, \fBalHP661XXA\fP, \fBalHP66XXA\fP, \fBalHP3640A\fP, \fBalN67XX\fP, \fBalDAQmx\fP, \fBalBILT\fP, \fBalBiltBE58x\fP, \fBalClient\fP, \fBalKiPlz\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBSAlimEnum\fP"

.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIalDebug \fP\fP
.TP
\fB\fIalAuto \fP\fP
.TP
\fB\fIalDAC488 \fP\fP
.TP
\fB\fIalHP661XXA \fP\fP
.TP
\fB\fIalHP66XXA \fP\fP
.TP
\fB\fIalHP3640A \fP\fP
.TP
\fB\fIalN67XX \fP\fP
.TP
\fB\fIalDAQmx \fP\fP
.TP
\fB\fIalBILT \fP\fP
.TP
\fB\fIalBiltBE58x \fP\fP
.TP
\fB\fIalClient \fP\fP
.TP
\fB\fIalKiPlz \fP\fP

.SH "Author"
.PP 
Generated automatically by Doxygen for Simulateur Banc from the source code\&.
