.TH "D:/cpp/simu_cpp/src/instruments/Alim/SAlimentations.cpp" 3 "Fri Apr 14 2017" "Simulateur Banc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/cpp/simu_cpp/src/instruments/Alim/SAlimentations.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SAlimentations\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "AnsiString \fBSAlimEnumStr\fP [\fBALIM_ENUM_LENGTH\fP] = {'alDebug', '\fBalAuto\fP', '\fBalDAC488\fP', '\fBalHP661XXA\fP', '\fBalHP66XXA\fP', '\fBalHP3640A\fP', '\fBalN67XX\fP', '\fBalDAQmx\fP', '\fBalBILT\fP', '\fBalBiltBE58x\fP', '\fBalClient\fP', '\fBalKiPlz\fP'}"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "AnsiString \fBSAlimEnumStr\fP[\fBALIM_ENUM_LENGTH\fP] = {'alDebug', '\fBalAuto\fP', '\fBalDAC488\fP', '\fBalHP661XXA\fP', '\fBalHP66XXA\fP', '\fBalHP3640A\fP', '\fBalN67XX\fP', '\fBalDAQmx\fP', '\fBalBILT\fP', '\fBalBiltBE58x\fP', '\fBalClient\fP', '\fBalKiPlz\fP'}"

.SH "Author"
.PP 
Generated automatically by Doxygen for Simulateur Banc from the source code\&.
