.TH "D:/cpp/simu_cpp/src/instruments/Alim/virtual_Alimentation_C.cpp" 3 "Fri Apr 14 2017" "Simulateur Banc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/cpp/simu_cpp/src/instruments/Alim/virtual_Alimentation_C.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'virtual_Alimentation_C\&.h'\fP
.br
\fC#include 'hp661xxa_C\&.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBALIM_ENUM_LENGTH\fP   12"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBALIM_ENUM_LENGTH\fP   12"

.SH "Author"
.PP 
Generated automatically by Doxygen for Simulateur Banc from the source code\&.
