.TH "vsim_C" 3 "Jeudi Mai 18 2017" "Alimentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vsim_C \- 
.PP
definit la classe virtuelle des instruments Alimentation simulés \&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'instruments\\Alim\\SAlimentations\&.h'\fP
.PP
Dérivée par \fBvirtual_alimentation_C\fP\&.
.SH "Description détaillée"
.PP 
definit la classe virtuelle des instruments Alimentation simulés \&. 

.PP
.nf
 \version : 1.0
.fi
.PP
 
.PP
\fBDate:\fP
.RS 4
: 13/04/2017
.RE
.PP
.PP
.nf
 \version : 1.0
.fi
.PP
 
.PP
\fBDate:\fP
.RS 4
: 6/04/2017 
.RE
.PP


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Alimentation à partir du code source\&.
