.TH "D:/cpp/simu_cpp/src/equipment/Recepteur/virtual_receiver_C.h" 3 "Fri Apr 14 2017" "Simulateur Banc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/cpp/simu_cpp/src/equipment/Recepteur/virtual_receiver_C.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'virtual_equipment_C\&.h'\fP
.br
\fC#include <IniFiles\&.hpp>\fP
.br
\fC#include <time\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTCompEqpt\fP"
.br
.ti -1c
.RI "class \fBvirtual_receiver_C\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBequipmentEnum\fP { \fBRX\fP, \fBDOCON\fP, \fBUPCON\fP, \fBDUAL\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBequipmentEnum\fP"

.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIRX \fP\fP
.TP
\fB\fIDOCON \fP\fP
.TP
\fB\fIUPCON \fP\fP
.TP
\fB\fIDUAL \fP\fP

.SH "Author"
.PP 
Generated automatically by Doxygen for Simulateur Banc from the source code\&.
