.TH "Alimentation" 3 "Mercredi Octobre 25 2017" "Simulateur Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Alimentation \- 
.SH SYNOPSIS
.br
.PP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "double \fBvoltage_m\fP"
.br
.RI "\fIvoltage_m : voltage desire \fP"
.ti -1c
.RI "double \fBvoltage_actif_m\fP"
.br
.RI "\fIvoltage_actif_m : voltage actif \fP"
.ti -1c
.RI "double \fBcurrent_m\fP"
.br
.RI "\fIcurrent_m : courant desire \fP"
.ti -1c
.RI "double \fBcurrent_actif_m\fP"
.br
.RI "\fIcurrent_actif_m : courant actif \fP"
.ti -1c
.RI "double \fBvoltageMax_m\fP"
.br
.RI "\fIvoltageMax_m : Tension Max autorisée \fP"
.ti -1c
.RI "double \fBcourantMin_m\fP"
.br
.RI "\fIvoltageMin_m : Tension Min autorisée \fP"
.ti -1c
.RI "double \fBcourantMax_m\fP"
.br
.RI "\fIvoltageMin_m : Tension Min autorisée \fP"
.ti -1c
.RI "double \fBpuissance_m\fP"
.br
.RI "\fIPuissance de l'equipement : Tension Min autorisée\&. \fP"
.ti -1c
.RI "double \fBpuissanceMax_m\fP"
.br
.RI "\fIpuissanceMax_m : puissance Maximal autorisée \fP"
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Simulateur Documentation à partir du code source\&.
