.TH "errorInfo_C" 3 "Mercredi Octobre 25 2017" "Simulateur Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
errorInfo_C \- 
.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "void \fBprint\fP ()"
.br
.ti -1c
.RI "void \fBgetStrMsg\fP (string *strMsg_o)"
.br
.in -1c
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "string \fBerrClass_m\fP"
.br
.ti -1c
.RI "string \fBerrStack_m\fP"
.br
.ti -1c
.RI "string \fBerrMsg_m\fP"
.br
.ti -1c
.RI "string \fBerrCodeMsg_m\fP"
.br
.ti -1c
.RI "string \fBprocessName_m\fP"
.br
.ti -1c
.RI "long \fBerrCode_m\fP"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Simulateur Documentation à partir du code source\&.
