.TH "Frequency" 3 "Mercredi Octobre 25 2017" "Simulateur Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Frequency \- 
.SH SYNOPSIS
.br
.PP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "double \fBfrequency_Start_In\fP"
.br
.RI "\fIFrequence de depart entrante\&. \fP"
.ti -1c
.RI "double \fBfrequency_Stop_In\fP"
.br
.RI "\fIFrequence de fin entrante\&. \fP"
.ti -1c
.RI "double \fBbandwidth\fP"
.br
.RI "\fIBande passante\&. \fP"
.ti -1c
.RI "double \fBstep\fP"
.br
.RI "\fIEtape\&. \fP"
.ti -1c
.RI "double \fBfrequency_Min\fP"
.br
.RI "\fIFrequence minimum\&. \fP"
.ti -1c
.RI "double \fBfrequency_Max\fP"
.br
.RI "\fIFrequence maximum\&. \fP"
.ti -1c
.RI "double \fBfrequency_Ol\fP"
.br
.RI "\fIFrequence oscillateur local\&. \fP"
.ti -1c
.RI "double \fBfrequencyOlMax\fP"
.br
.RI "\fIFrequence oscillateur local\&. \fP"
.ti -1c
.RI "double \fBfrequencyOlMin\fP"
.br
.RI "\fIFrequence oscillateur local\&. \fP"
.ti -1c
.RI "double \fBpower_Ol\fP"
.br
.RI "\fIPuissance oscillateur local\&. \fP"
.ti -1c
.RI "double \fBpowerOlMax\fP"
.br
.RI "\fIPuissance oscillateur local\&. \fP"
.ti -1c
.RI "double \fBpowerOlMin\fP"
.br
.RI "\fIPuissance oscillateur local\&. \fP"
.ti -1c
.RI "double \fBpower_min\fP"
.br
.RI "\fIPuissance minimum\&. \fP"
.ti -1c
.RI "double \fBpower_max\fP"
.br
.RI "\fIPuissance maximum\&. \fP"
.ti -1c
.RI "double \fBpower_in\fP"
.br
.RI "\fIPuissance entrante\&. \fP"
.ti -1c
.RI "double \fBpower_out\fP"
.br
.RI "\fIPuissance de sortie\&. \fP"
.ti -1c
.RI "double \fBgain\fP"
.br
.RI "\fIGain obtenu\&. \fP"
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Simulateur Documentation à partir du code source\&.
