.TH "Interface" 3 "Mercredi Octobre 25 2017" "Simulateur Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Interface \- 
.PP
Definit la class d'interface materiel Gpib \&.  

.SH SYNOPSIS
.br
.PP
.SH "Description détaillée"
.PP 
Definit la class d'interface materiel Gpib \&. 

.PP
.nf
 \version : 1.0
.fi
.PP
 
.PP
\fBDate:\fP
.RS 4
: 06/04/2017 
.RE
.PP


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Simulateur Documentation à partir du code source\&.
