.TH "SAdrsStruct" 3 "Mercredi Octobre 25 2017" "Simulateur Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SAdrsStruct \- 
.SH SYNOPSIS
.br
.PP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "AnsiString \fBDeviceName\fP"
.br
.RI "\fIChaine de caracteres contenant : Nom de l'instrument\&. \fP"
.ti -1c
.RI "AnsiString \fBAddress\fP"
.br
.RI "\fIChaine de caracteres contenant : Adresse de l'instrument\&. \fP"
.ti -1c
.RI "AnsiString \fBLibrary\fP"
.br
.RI "\fIChaine de caracteres contenant : Librairie utilisee\&. \fP"
.ti -1c
.RI "AnsiString \fBDeviceType\fP"
.br
.RI "\fIChaine de caracteres contenant : Type d'instrument\&. \fP"
.ti -1c
.RI "AnsiString \fBFDescription\fP"
.br
.RI "\fIChaine de caracteres contenant : Description de l'instrument\&. \fP"
.ti -1c
.RI "AnsiString \fBComment\fP"
.br
.RI "\fIChaine de caracteres contenant : Commentaire(s) \fP"
.ti -1c
.RI "int \fBInUse\fP"
.br
.RI "\fIVariable de type int : utilisation des instruments\&. \fP"
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Simulateur Documentation à partir du code source\&.
