.TH "SRxThread" 3 "Mercredi Octobre 25 2017" "Simulateur Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRxThread \- 
.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "__fastcall \fBSRxThread\fP (bool CreateSuspended)"
.br
.in -1c
.SS "Fonctions membres protégées"

.in +1c
.ti -1c
.RI "void __fastcall \fBExecute\fP ()"
.br
.ti -1c
.RI "void __fastcall \fBUpdateIhm\fP ()"
.br
.ti -1c
.RI "void __fastcall \fBMonitoring\fP ()"
.br
.ti -1c
.RI "void __fastcall \fBGentleStop\fP ()"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "long \fBstop_m\fP"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Simulateur Documentation à partir du code source\&.
