.TH "TAboutForm" 3 "Mercredi Octobre 25 2017" "Simulateur Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TAboutForm \- 
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBTChildForm\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "void __fastcall \fBFormResize\fP (TObject *Sender)"
.br
.ti -1c
.RI "void __fastcall \fBFormShow\fP (TObject *Sender)"
.br
.ti -1c
.RI "virtual __fastcall \fBTAboutForm\fP (TComponent *AOwner)"
.br
.ti -1c
.RI "void \fBDeclareDepends\fP (TStringList *StrList)"
.br
.in -1c
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "TLabel * \fBProductNameLabel\fP"
.br
.ti -1c
.RI "TLabel * \fBFileDescriptionLabel\fP"
.br
.ti -1c
.RI "TLabel * \fBLegalCopyRightLabel\fP"
.br
.ti -1c
.RI "TLabel * \fBCompanyNameLabel\fP"
.br
.ti -1c
.RI "TLabel * \fBFileVersionLabel\fP"
.br
.ti -1c
.RI "TPanel * \fBAdvPanel1\fP"
.br
.ti -1c
.RI "TGroupBox * \fBAdvGroupBox1\fP"
.br
.ti -1c
.RI "TStringGrid * \fBAboutGrid\fP"
.br
.ti -1c
.RI "TMemo * \fBHistMemo\fP"
.br
.ti -1c
.RI "TRelativePanel * \fBRelativePanel1\fP"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Simulateur Documentation à partir du code source\&.
