.TH "TAlimThread" 3 "Mercredi Octobre 25 2017" "Simulateur Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TAlimThread \- 
.PP
Definit la class du Thread de l'objet \fBAlimentation\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SAlimThread\&.h>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "__fastcall \fBTAlimThread\fP (bool CreateSuspended, \fBSAlimentations\fP *Alim)"
.br
.in -1c
.SS "Fonctions membres protégées"

.in +1c
.ti -1c
.RI "void __fastcall \fBsetAlim\fP (\fBSAlimentations\fP *A)"
.br
.ti -1c
.RI "void __fastcall \fBExecute\fP ()"
.br
.ti -1c
.RI "void __fastcall \fBUpdateIhm\fP ()"
.br
.ti -1c
.RI "void __fastcall \fBGentleStop\fP ()"
.br
.ti -1c
.RI "void __fastcall \fBmonitoringParam\fP ()"
.br
.in -1c
.SS "Attributs protégés"

.in +1c
.ti -1c
.RI "long \fBstop_m\fP"
.br
.ti -1c
.RI "\fBSAlimentations\fP * \fBAlim\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Definit la class du Thread de l'objet \fBAlimentation\fP\&. 

.PP
.nf
 \version : 1.0
.fi
.PP
 
.PP
\fBDate:\fP
.RS 4
: 17/10/2017 
.RE
.PP


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Simulateur Documentation à partir du code source\&.
