.TH "TBenchFormUnit" 3 "Mercredi Octobre 25 2017" "Simulateur Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TBenchFormUnit \- 
.PP
Definit la class d'interface Homme/Machine du Bench \&.  classe herite de la classe \fBTSimuForm\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SBenchFormUnit\&.h>\fP
.PP
Est dérivée de \fBTSimuForm\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "void \fBgetListDevice\fP ()"
.br
.ti -1c
.RI "__fastcall \fBTBenchFormUnit\fP (TComponent *Owner)"
.br
.in -1c
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "TPanel * \fBPanel1\fP"
.br
.ti -1c
.RI "TEdit * \fBTextName\fP"
.br
.ti -1c
.RI "TEdit * \fBTextImmo\fP"
.br
.ti -1c
.RI "TLabel * \fBLabelImmo\fP"
.br
.ti -1c
.RI "TLabel * \fBLabelName\fP"
.br
.ti -1c
.RI "TGroupBox * \fBGroupBox1\fP"
.br
.ti -1c
.RI "TLabel * \fBLabel1\fP"
.br
.ti -1c
.RI "TLabel * \fBLabel2\fP"
.br
.ti -1c
.RI "TLabel * \fBLabel3\fP"
.br
.ti -1c
.RI "TGroupBox * \fBGroupBox2\fP"
.br
.ti -1c
.RI "TLabel * \fBLabel4\fP"
.br
.ti -1c
.RI "TListView * \fBListView1\fP"
.br
.ti -1c
.RI "TLabel * \fBLabel5\fP"
.br
.ti -1c
.RI "TEdit * \fBTCal_In\fP"
.br
.ti -1c
.RI "TEdit * \fBTCal_Out\fP"
.br
.ti -1c
.RI "TLabel * \fBLabel6\fP"
.br
.ti -1c
.RI "TEdit * \fBTCal_Spectrum\fP"
.br
.ti -1c
.RI "TLabel * \fBLabel7\fP"
.br
.ti -1c
.RI "TAdvSmoothLedLabel * \fBTextTension\fP"
.br
.ti -1c
.RI "TAdvSmoothLedLabel * \fBTextCourant\fP"
.br
.ti -1c
.RI "TAdvSmoothLedLabel * \fBTextPower\fP"
.br
.ti -1c
.RI "TBitBtn * \fBBitBtn1\fP"
.br
.ti -1c
.RI "\fBSBench_C\fP * \fBDevice_m\fP"
.br
.ti -1c
.RI "__property \fBSBench_C\fP * \fBDevice\fP = {read = Device_m, write = Device_m}"
.br
.in -1c
.SH "Description détaillée"
.PP 
Definit la class d'interface Homme/Machine du Bench \&.  classe herite de la classe \fBTSimuForm\fP\&. 

.PP
.nf
 \version : 1.0
.fi
.PP
 
.PP
\fBDate:\fP
.RS 4
: 17/10/2017 
.RE
.PP


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Simulateur Documentation à partir du code source\&.
