.TH "TCompEqpt" 3 "Mercredi Octobre 25 2017" "Simulateur Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TCompEqpt \- 
.PP
Structure de l'equipement\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <virtual_receiver_C\&.h>\fP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "int \fBnb_Tranche\fP"
.br
.RI "\fInb_Tranche : nombre de tranche \fP"
.ti -1c
.RI "int \fBnb_Alim\fP"
.br
.RI "\fInb_Alim : nombre d'alimentation \fP"
.ti -1c
.RI "int \fBnb_Tmtc\fP"
.br
.RI "\fInb_Tmtc : nombre de tmtc \fP"
.in -1c
.SH "Description détaillée"
.PP 
Structure de l'equipement\&. 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Simulateur Documentation à partir du code source\&.
