.TH "TLogForm" 3 "Mercredi Octobre 25 2017" "Simulateur Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TLogForm \- 
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de \fBTChildForm\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "void __fastcall \fBClearButtonClick\fP (TObject *Sender)"
.br
.ti -1c
.RI "void __fastcall \fBFormClose\fP (TObject *Sender, TCloseAction &Action)"
.br
.ti -1c
.RI "void \fBAddColoredLine\fP (AnsiString AText, TColor AColor)"
.br
.ti -1c
.RI "__fastcall \fBTLogForm\fP (TComponent *Owner)"
.br
.in -1c
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "TRichEdit * \fBMsgMemo\fP"
.br
.ti -1c
.RI "TPanel * \fBPanel1\fP"
.br
.ti -1c
.RI "TButton * \fBClearButton\fP"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Simulateur Documentation à partir du code source\&.
