.TH "TMainUnit" 3 "Mercredi Octobre 25 2017" "Simulateur Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMainUnit \- 
.PP
Definit la class pricipale du programme\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MainUnit\&.h>\fP
.SH "Description détaillée"
.PP 
Definit la class pricipale du programme\&. 

.PP
.nf
 \version : 1.0
.fi
.PP
 
.PP
\fBDate:\fP
.RS 4
: 17/10/2017 
.RE
.PP


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Simulateur Documentation à partir du code source\&.
