.TH "Utils::InstObserver" 3 "Mercredi Octobre 25 2017" "Simulateur Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utils::InstObserver \- 
.SH SYNOPSIS
.br
.PP
.PP
Dérivée par \fBRx_C\fP, et \fBSBench_C\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "virtual void \fBChangeValueDown\fP (std::string value, TYPE_PARAM type)=0"
.br
.ti -1c
.RI "virtual void \fBChangeValueDown\fP (int value, TYPE_PARAM type)=0"
.br
.ti -1c
.RI "virtual void \fBChangeValueDown\fP (double value, TYPE_PARAM type)=0"
.br
.ti -1c
.RI "virtual void \fBChangeValueDown\fP (bool value, TYPE_PARAM type)=0"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Simulateur Documentation à partir du code source\&.
