.TH "virtual_tmtc_C" 3 "Mercredi Octobre 25 2017" "Simulateur Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
virtual_tmtc_C \- 
.PP
Classe du tmtc virtuel\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <virtual_tmtc_C\&.h>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBvirtual_tmtc_C\fP ()"
.br
.RI "\fIConstructeur de la fonction \fBvirtual_tmtc_C\fP\&. \fP"
.ti -1c
.RI "\fB~virtual_tmtc_C\fP ()"
.br
.RI "\fIDestructeur de la fonction \fBvirtual_tmtc_C\fP\&. \fP"
.in -1c
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "__property bool \fBTm_Status\fP = {read = getTm_Status, write = setTm_Status}"
.br
.RI "\fIPropriete Tm_Status de l'objet \fBvirtual_tmtc_C\fP\&. \fP"
.ti -1c
.RI "__property bool \fBTm_ON_OFF\fP = {read = getTm_ON_OFF, write = setTm_ON_OFF}"
.br
.RI "\fIPropriete Tm_ON_OFF de l'objet \fBvirtual_tmtc_C\fP\&. \fP"
.in -1c
.SH "Description détaillée"
.PP 
Classe du tmtc virtuel\&. 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Simulateur Documentation à partir du code source\&.
