.TH "visaDefaultRM_C" 3 "Mercredi Octobre 25 2017" "Simulateur Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
visaDefaultRM_C \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <visa_C\&.h>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "void \fBOpenDefaultRm\fP ()"
.br
.ti -1c
.RI "void \fBCloseDefaultRm\fP ()"
.br
.in -1c
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "unsigned long \fBsess_m\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Classe Visa niveau carte\&. 
.SH "Documentation des fonctions membres"
.PP 
.SS "void \fBvisaDefaultRM_C::CloseDefaultRm\fP (void)"
Methode de fermeture session VISA au niveau carte\&. 
.SS "void \fBvisaDefaultRM_C::OpenDefaultRm\fP (void)"
Methode d'ouverture session VISA au niveau carte\&. 
.SH "Documentation des données membres"
.PP 
.SS "unsigned long \fBvisaDefaultRM_C::sess_m\fP"
Variable membre contenant le numéro de session VISA au niveau carte\&. 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Simulateur Documentation à partir du code source\&.
